name: deployment

on: 
  push:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests 
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm build

      - name: Deploy project
        run: echo "Deploying project in Azure Cloud"
